# Form implementation generated from reading ui file 'sampleUi01.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    """
    Ui_MainWindow is a class that defines the user interface for a QMainWindow using PyQt.
    Attributes:
        controller (object, optional): An optional controller object. If provided, it is used to connect button signals to controller methods.
    Methods:
        __init__(self, controller=None):
            Initializes the Ui_MainWindow instance and optionally sets a controller.
        setupUi(self, MainWindow):
            Sets up the UI components for the given MainWindow instance, including a central widget, a push button, a menu bar with a sample menu, and a status bar.
            - The push button's click event is connected to `controller.quitApp` if a controller is provided, otherwise it prints a message.
            - Adds a menu with an action to the menu bar.
        retranslateUi(self, MainWindow):
            Sets the display text for all UI components, supporting internationalization.
    """
    def __init__(self, controller=None):
        self.controller = controller

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.pbOne = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pbOne.setGeometry(QtCore.QRect(180, 60, 75, 23))
        self.pbOne.setObjectName("pbOne")
        if self.controller:
            self.pbOne.clicked.connect(self.controller.quitApp)
        else:
            self.pbOne.clicked.connect(lambda: print("Button clicked!"))
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuSample_Window = QtWidgets.QMenu(parent=self.menubar)
        self.menuSample_Window.setObjectName("menuSample_Window")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMenu_01 = QtGui.QAction(parent=MainWindow)
        self.actionMenu_01.setObjectName("actionMenu_01")
        self.menuSample_Window.addAction(self.actionMenu_01)
        self.menubar.addAction(self.menuSample_Window.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbOne.setText(_translate("MainWindow", "Sample Bt 01"))
        self.menuSample_Window.setTitle(_translate("MainWindow", "Sample Menu"))
        self.actionMenu_01.setText(_translate("MainWindow", "Menu 01"))



